@echo off
echo Starting Agiliza CRM...
echo Starting Backend...
start cmd /k "python -m uvicorn backend.main:app --reload"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo Done! Access http://localhost:5173
